services:
  knowyoursos-configurationserver:
    build:
        context: ./KnowYourSOS-ConfigurationServer
        dockerfile: ../Dockerfile
        args:
          SERVICE_NAME: ConfigurationServer
    container_name: knowyoursos-configurationserver
    environment:
      - SERVICE_TO_WAIT_FOR=None
    networks:
      - backend
  knowyoursos-eurekaserver:
    build:
      context: ./KnowYourSOS-EurekaServer
      dockerfile: ../Dockerfile
      args:
        SERVICE_NAME: EurekaServer
    container_name: knowyoursos-eurekaserver
    environment:
      - SERVICE_TO_WAIT_FOR=knowyoursos-configurationserver:8888 
    depends_on:
      - knowyoursos-configurationserver
    networks:
      - backend
  knowyoursos-apigateway:
    build:
      context: ./KnowYourSOS-ApiGateway
      dockerfile: ../Dockerfile
      args:
        SERVICE_NAME: UpdateDBMicroservice
    container_name: knowyoursos-apigateway
    ports:
          - "8222:8222"
    depends_on:
      - knowyoursos-eurekaserver
    environment:
      - SERVICE_TO_WAIT_FOR=knowyoursos-eurekaserver:8761
    networks:
      - backend
  knowyoursos-sosnumbermicroservice:
    build:
      context: ./KnowYourSOS-SOSNumberMicroservice
      dockerfile: ../Dockerfile
      args:
        SERVICE_NAME: UpdateDBMicroservice
    container_name: knowyoursos-sosnumbermicroservice
    depends_on:
      - knowyoursos-eurekaserver
    environment:
      - SERVICE_TO_WAIT_FOR=knowyoursos-eurekaserver:8761
    networks:
      - backend
  knowyoursos-updatedbmicroservice:
    build:
      context: ./KnowYourSOS-UpdateDBMicroservice
      dockerfile: ../Dockerfile
      args:
        SERVICE_NAME: UpdateDBMicroservice
    container_name: knowyoursos-updatedbmicroservice
    depends_on:
      - knowyoursos-eurekaserver
    environment:
      - SERVICE_TO_WAIT_FOR=knowyoursos-eurekaserver:8761
    networks:
      - backend
  knowyoursos-sosdatabase:
    image: postgres:15
    environment:
      POSTGRES_DB: sosnumbers
      POSTGRES_USER: sosmicroservice
      POSTGRES_PASSWORD: TH1sI_sASecurePw0rD!
    ports:
      - "5432:5432"
    networks:
      - backend
networks:
  backend:
    driver: bridge
